apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "base.fullname" . }}:{{ .Values.image.tag | default .Chart.AppVersion }}
  source:
    git:
      uri: {{ .Values.git.url }}
      ref: {{ .Values.git.ref }}
    type: Git
  strategy:
    dockerStrategy:
      env:
      - name: SKIP_TESTS
        value: "{{ .Values.buildConfig.skipTests }}"
      - name: APPLICATION
        value: {{ .Values.buildConfig.application }}
      - name: CONFIGURATION
        value: {{ .Values.buildConfig.configuration }}
    type: Docker